const CartActionTypes = {
    CALL_CART_IN: 'CALL_CART_IN',
    CALL_CART_OFF: 'CALL_CART_OFF',
    ADD_ITEM: 'ADD_ITEM',
    REMOVE_ITEM: 'REMOVE_ITEM',
    CLEAR_ITEM_FROM_CART: 'CLEAR_ITEM_FROM_CART',
    RESET_CART: 'RESET_CART'
}
export default CartActionTypes;